export const LOADING = "LOADING";
//users
export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const FETCH_USER_DATA_FAILED = "FETCH_USER_DATA_FAILED";

export const FETCH_ECOSYSTEMS = "FETCH_ECOSYSTEMS";
export const FETCH_ECOSYSTEMS_FAILED = "FETCH_ECOSYSTEMS_FAILED";

export const FETCH_HUBS= "FETCH_HUBS";
export const FETCH_HUBS_FALIED = "FETCH_HUB_FAILED";

export const FETCH_STATIONS = "FETCH_STATIONS";
export const FETCH_STATIONS_FAILED = "FETCH_STATIONS_FAILED";

export const FETCH_DRONES = "FETCH_DRONE";
export const FETCH_DRONES_FAILED = "FETCH_DRONES_FAILED";

export const FETCH_BATTERY = "FETCH_FETCH_BATTERY";
export const FETCH_BATTERY_FAILED = "FETCH_BATTERY_FAILED";

export const FETCH_PAYLOAD = "FETCH_PAYLOAD";
export const FETCH_PAYLOAD_FAILED = "FETCH_PAYLOAD_FAILED";

export const FETCH_SEONSOR = "FETCH_SENSOR";
export const FETCH_SEONSOR_FAILED = "FETCH_SEONSOR_FAILED";

export const FETCH_ORGANIZATION = "FETCH_ORGANIZATION";
export const FETCH_ORGANIZATION_FAILED = "FETCH_ORGANIZATION_FAILED";

export const ACCEPT_REQUEST= "ACCEPT_REQUEST";
export const ACCEPT_REQUEST_FAILED = "ACCEPT_REQUEST_FAILED";

export const REJECT_REQUEST = "REJECT_REQUEST";
export const REJECT_REQUEST_FAILED = "REJECT_REQUEST_FAILED";
